# Generated by Django 4.2.9 on 2024-02-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='sender',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
